image: node:latest

# List of stages for jobs, and their order of execution
stages:
  - build
  - test

# This job runs in the build stage, which runs first.
build-job:
  stage: build
  before_script:
    - echo "Launching the project..."
    - npm install --inlcude dev
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

# This job runs in the test stage.
unit-test-job:
  stage: test
  script:
    - npm run dev
